#!/bin/bash

# Make sure everything is development forever
export NODE_ENV=development

# Load environment specific environment variables

#export HUBOT_VC_SHARE_ORGANIZATION=First segment of your VividCortex URL
#export HUBOT_VC_SHARE_ENVIRONMENT=Second segment of your VividCortex URL
#export HUBOT_VC_SHARE_TOKEN=Your VividCortex installation token

if [ -f .env ]; then
  source .env
fi

if [ -f .env.${NODE_ENV} ]; then
  source .env.${NODE_ENV}
fi

npm install

# Make sure coffee and mocha are on the path
export PATH="node_modules/.bin:$PATH"
